# Generated by Django 4.0.5 on 2022-06-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_boost_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core',
            old_name='damage',
            new_name='hp',
        ),
    ]
