# Generated by Django 4.0.5 on 2022-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_core_damage_alter_boost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'casual'), (1, 'auto')], default=0),
        ),
        migrations.AlterField(
            model_name='core',
            name='damage',
            field=models.IntegerField(default=models.IntegerField(default=10)),
        ),
    ]
