# Generated by Django 4.0.5 on 2022-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_boost_type_alter_core_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='hp_boss',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='core',
            name='level_enemy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='core',
            name='damage',
            field=models.IntegerField(default=10),
        ),
    ]
